### ISSUE TITLE
error when i says "liste-de-courses"

### ISSUE THREAD

**Issue by mathieusayag** [bacardi55/kalliope-todotxt#2]
hello

i have a problem when i start the todotxt.  can i help me ?

Thank you
```
Google Speech Recognition thinks you said liste de courses
Order matched in the brain. Running synapse "liste-de-courses"
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 1060, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 263, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 274, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 120, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/SynapseLauncher.py", line 104, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/todotxt/todotxt.py", line 27, in __init__
    self.say({'action': self.configuration['action'], 'task_list': task_list, 'count': len(task_list)})
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronModule.py", line 151, in say
    tts_message = self._get_message_from_dict(message)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronModule.py", line 203, in _get_message_from_dict
    returned_message = self._get_file_template(self.file_template, message_dict)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronModule.py", line 220, in _get_file_template
    % real_file_template_path)
TemplateFileNotFoundException: Template file None not found in templates folder
```

**Comment by mathieusayag** [comment]
i find my error, i don't move the template's file.

Sorry
